In [4]:
from IPython.core.debugger import set_trace
import os
class Metrics(object):
    data_path = "data/metrics/"
    def start(self):
        data = self.read_data(data_path)
        
class MediforData():
    ref_mask = None
    sys_mask = None
    
    def __init__(self, ref, sys):
        self.ref_mask = ref
        self.sys_mask = sys
    

In [5]:
def read_data(self):
    folders = self._get_folders()
    data = []
    for folder in folders:
        data.append(MediforData(get_images(folder))
    return data    

        
def _get_folders(self, directory):
    subfolders = [f.path for f in os.scandir(directory) if f.is_dir() ]
    print(subfolders)
    return None
                    
Metrics.read_data = read_data
Metrics._get_folders = _get_folders 
Metrics.start = start
metric = Metrics()
metric.start()

SyntaxError: invalid syntax (<ipython-input-5-b740dec443b5>, line 6)

In [13]:
%%timeit
import numpy as np

result = np.random.randint(255, size=(50, 50))
result = np.where(result == 255, 0 , result)
result = np.where(result == 510, 255 , result)

22.3 µs ± 1.81 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [35]:
#%%timeit
import numpy as np

result = np.random.randint(255, size=(4, 4))
print(result)
flat = result.ravel()
indexes = np.array([1,5,6,8])
filtered = flat[indexes]
print(filtered)

[[ 24 110 246 228]
 [ 43 109 251  40]
 [141 109 248 113]
 [ 44 143 190  34]]
[110 109 251 141]
